version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./back-end
      dockerfile: Dockerfile
    # ports:
    #   - "8000:8000"
    volumes:
      - ./back-end/myproject/:/usr/src/app
      # - ./uploads/:/uploads
    env_file:
      - .env
    networks:
      - local_network

  frontend:
    container_name: frontend
    build:
      context: ./front-end
      dockerfile: Dockerfile
    # ports:
    #   - "3000:3000"
    volumes:
      - ./front-end/my-app/:/app
    env_file:
      - .env
    networks:
      - local_network

  nginx:
    depends_on:
      - backend
      - frontend
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/config.conf:/etc/nginx/conf.d/default.conf
    # volumes:
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      # - static_volume:/static
      # - media_volume:/media
    ports:
      - "80:80"
    networks:
      - local_network

networks:
  local_network:
    driver: bridge