FROM node:18

RUN apt-get update && apt-get install -y nginx

WORKDIR /usr/share/nginx/html

COPY . ./

RUN npm install

RUN npm run build

COPY ../nginx/product.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]