# Generated by Django 4.2 on 2024-12-21 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.CharField(default='Uncategorized', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='article',
            name='height',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AddField(
            model_name='article',
            name='how_many_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='how_many_times_ordered',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(default='untyped', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='width',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='article',
            name='src',
            field=models.URLField(max_length=100),
        ),
    ]
