# Generated by Django 4.2 on 2024-12-21 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_article_id_article_item_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
