# Generated by Django 4.2 on 2024-12-22 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_article_categories_alter_article_height_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='categories',
            new_name='category',
        ),
    ]
