FROM python:3.11-slim

RUN apt-get update && \
    apt-get install -y \
    libcairo2 \
    libpango1.0-0 \
    libgdk-pixbuf2.0-0

WORKDIR /usr/src/app

# Install dependencies
COPY requirements.txt .
RUN pip install -r requirements.txt

CMD ["gunicorn", "myproject.wsgi:application", "--bind", "0.0.0.0:8000"]